development:
  blog_title: Lenon Marcel
  blog_description: forever programmer (development)
  mongodb:
    database: app_blog_development

test:
  blog_title: Lenon Marcel
  blog_description: forever programmer (test)
  mongodb:
    database: app_blog_test

production:
  blog_title: Lenon Marcel
  blog_description: forever programmer
  mongodb:
    database: app_blog_production
