development:
  blog_title: Lenon Marcel
  blog_description: forever programmer (development)
  fbapp_id: 152943078134721
  mongodb:
    database: app_blog_development

test:
  blog_title: Lenon Marcel
  blog_description: forever programmer (test)
  fbapp_id: 152943078134721
  mongodb:
    database: app_blog_test

production:
  blog_title: Lenon Marcel
  blog_description: forever programmer
  fbapp_id: 152943078134721
  mongodb:
    database: app_blog_production
