test:
  cookie_key   : "blogsession"
  cookie_domain: ".example.com"
  cookie_secret: "secret key"
  assets_domain: "assets.example.com"
  blogs:
    - domain: "defaultblog.com"
      title: "default blog"
      description: "default blog description"
      home_title: "default blog home page"
      post_title: "%s | default blog"
    - domain: "other.example.com"
      title: "my other blog"
      description: "other blog description"
      home_title: "my other blog home page"
      post_title: "%s | my other blog"
