test:
  cookie_key       : "blogsession"
  cookie_secret    : "top secret key"
  blog_title       : "blog title"
  blog_description : "blog description"
  disqus_shortname : "example"
  gravatar_email   : "mail@example.com"
  author_name      : "blog author"
  author_bio       : "author bio"
  analytics_ua     : "UA-XXXXXXXX-X"
