test:
  cookie_key   : "blogsession"
  cookie_domain: ".example.com"
  cookie_secret: "secret key"
  assets_domain: "assets.example.com"
  blogs:
    - domain: ~
      title: "my blog"
      description: "blog description"
    - domain: "other.example.com"
      title: "my other blog"
      description: "other blog description"
